spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/smarthome"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql