server:
  port: 8082
spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/commerce?currentSchema=store
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
    instance-id: shopping-store:${random.value}